### ISSUE TITLE
Suggesting Enhancements: Supports for Custom Http Status Code in Controllers

### ISSUE THREAD

**Issue by dhamanutd** [sev-2/raiden#32]
## Reason
Current controllers seems only returns either 200 or 500 if something wrong happened.
There is possibility backend service should returns 400, 401, 403 instead of just error 500.

## Suggestion
Support return error with certain status code

**Comment by toopay** [comment]
@dhamanutd can you elaborate on actual use-case of this limitation? cc @vani-rf

**Comment by dhamanutd** [comment]
@toopay apparently we can already use raiden.ErrorResponse struct to return to specific status code.

I think this is can be improved on the documentation instead.
